#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 22 10:43:48 2021

@author: zhanghanqing
"""

# Problem set 2
# 1
balance = 484
annualInterestRate = 0.2
monthlyPaymentRate = 0.04
iteration = 1

while iteration <= 12:
    
     min_p = balance*monthlyPaymentRate
     balance -= min_p
     balance += (annualInterestRate/12)*balance
     iteration += 1

print('Remaining balance:',round(balance,2))