#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct  1 17:14:49 2021

@author: zhanghanqing
"""

def genPrimes():
    
    primes = [2]
    yield primes[0]
    guess = 3
    
    while True:
        if all(guess%x != 0 for x in primes):
            primes.append(guess)
        if guess == primes[-1]:
           yield primes[-1]
        guess += 1
    


           
p = genPrimes()
print(p)
p.__next__()
        